language: perl
perl:
  - "5.28"

cache:
  directories:
    - $HOME/perl5/perlbrew/perls/$TRAVIS_PERL_VERSION/lib/site_perl/
    - $HOME/perl5/perlbrew/perls/$TRAVIS_PERL_VERSION/bin/

install:
   - cpanm --quiet --notest --installdeps .

script:
   - prove -lr t/
